name: HelloWorld
main: net.dreamingraom.HelloWorld.HelloWorld
version: 0.1
commands:
  helloworld:
    description: This is a demo command.
    usage: /<command>
    permission: <plugin name>.helloworld
    permission-message: You don't have <permission>
permissions:
    helloworld.*:
        description: Gives access to all helloworld commands
        children:
            helloworld.helloworld: true
    helloworld.helloworld:
        description: HelloWorlds your chat.
        default: op
